### ISSUE TITLE
'Raw Preferences' does not reflect current preferences

### ISSUE THREAD

**Issue by achesak** [nim-lang/Aporia#114]
Change a setting in preferences (say, indent width from 2 to 4), then open up 'Raw Preferences' and it will still list the setting as the old value (indentWidth = 2).

**Comment by dom96** [comment]
Indeed. We need to modify the behaviour so that settings are saved under more circumstances, for example I get occasionally annoyed because Aporia doesn't save my tabs after it crashes. Saving the temp settings after each tab open/close would prevent this. But maybe there is a better way?
