### ISSUE TITLE
Dependencies with #head

### ISSUE THREAD

**Issue by davidsblog** [nim-lang/Aporia#135]
At the moment, I cannot build Aporia with nimble, I get an error about version conflicts of the GTK wrapper.  However, if I hack the `aporia.nimble` file and remove `#head` from the GTK2 dependency then it will build fine. So I'm wondering if the practice of using  `#head` in a dependency is more likely to break?  Would it be a more reliable build if dependencies always used a version number? Just a thought...

**Comment by dom96** [comment]
> So I'm wondering if the practice of using #head in a dependency is more likely to break?

No... if you're using a bleeding release of Nimble then things are likely to break: https://github.com/nim-lang/nimble/issues/289

**Comment by davidsblog** [comment]
Fair enough, I was just making a suggestion...  But I haven't figured out where to find a *stable* release of Aporia yet, so perhaps I should do that instead :-)

**Comment by dom96** [comment]
nimble install aporia should work now to get you a stable release of aporia. Nimble grabs the latest tagged version by default, which is typically more stable than the git HEAD.

**Comment by davidsblog** [comment]
That's great!  I've just done that and it has worked perfectly.  I appreciate that.

Out of curiosity, is there such a thing as a stable release of Nimble (I'm using Nim 0.15.2)?  I'm wondering if there is a better Nimble version than the one I'm using (I used the `install_nimble.nims` script from 0.15.2 to install it).  I'm guessing that has given me the bleeding edge release of Nimble.

**Comment by dom96** [comment]
The stable release of Nimble is typically the latest tagged release. The ``install_nimble.nims`` script shouldn't install bleeding edge, please report that on the Nim repo :)

**Comment by davidsblog** [comment]
Cool.  I will double-check versions from the `install_nimble.nims` and pulling the latest from GitHub just in case I've done something silly.  But if the script does give me the same version then I'll report it.  Cheers.
