### ISSUE TITLE
Aporia won't build on openbsd current

### ISSUE THREAD

**Issue by javan-z** [nim-lang/Aporia#142]
Attempting to build on OpenBSD current.  They changed their pthread_np implementation after release 5.9.  Not to sure how to work around yet.

/home/javan/app/Aporia-0.4.1/nimcache/stdlib_system.c:(.text+0x10d65): undefined reference to `pthread_threadid_np'
        ... clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dom96** [comment]
This should probably be reported in the [Nim](https://github.com/nim-lang/Nim) repo.

**Comment by javan-z** [comment]
Will file in Nim repo
