### ISSUE TITLE
installation failed on Ubuntu 18.04 [nimble]

### ISSUE THREAD

**Issue by Minimisthupper** [nim-lang/Aporia#149]
Tried to install aporia for nim-in-action. "nimble install utils" didn't helped.
`$ nimble install aporia
Downloading https://github.com/nim-lang/Aporia using git
  Verifying dependencies for aporia@0.4.2
      Info: Dependency on gtk2@>= 1.3 already satisfied
  Verifying dependencies for gtk2@1.3
      Info: Dependency on cairo@any version already satisfied
  Verifying dependencies for cairo@1.0
      Info: Dependency on dialogs@>= 1.1.1 already satisfied
  Verifying dependencies for dialogs@1.1.1
      Info: Dependency on gtk2@>= 1.0 already satisfied
  Verifying dependencies for gtk2@1.3
      Info: Dependency on cairo@any version already satisfied
  Verifying dependencies for cairo@1.0
 Installing aporia@0.4.2
   Building aporia/aporia using c backend
    Prompt: Build failed for 'aporia@0.4.2', would you like to try installing 'aporia@#head' (latest unstable)? [y/N]
    Answer: y
Downloading https://github.com/nim-lang/Aporia using git
  Verifying dependencies for aporia@#head
      Info: Dependency on gtk2@>= 1.3 already satisfied
  Verifying dependencies for gtk2@1.3
      Info: Dependency on cairo@any version already satisfied
  Verifying dependencies for cairo@1.0
      Info: Dependency on dialogs@>= 1.1.1 already satisfied
  Verifying dependencies for dialogs@1.1.1
      Info: Dependency on gtk2@>= 1.0 already satisfied
  Verifying dependencies for gtk2@1.3
      Info: Dependency on cairo@any version already satisfied
  Verifying dependencies for cairo@1.0
 Installing aporia@#head
   Building aporia/aporia using c backend
       Tip: 23 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: aporia
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/home/floyd/.nimble/bin/nim" c --noBabelPath -d:release --path:"/home/floyd/.nimble/pkgs/gtk2-1.3"  --path:"/home/floyd/.nimble/pkgs/cairo-1.0"  --path:"/home/floyd/.nimble/pkgs/dialogs-1.1.1"  --path:"/home/floyd/.nimble/pkgs/gtk2-1.3"  --path:"/home/floyd/.nimble/pkgs/cairo-1.0"  -o:"/tmp/nimble_4041/githubcom_nimlangAporia_#head/aporia" "/tmp/nimble_4041/githubcom_nimlangAporia_#head/aporia.nim"
        ... Output: Hint: used config file '/home/floyd/.choosenim/toolchains/nim-0.19.4/config/nim.cfg' [Conf]
        ... Hint: used config file '/tmp/nimble_4041/githubcom_nimlangAporia_#head/aporia.nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: aporia [Processing]
        ... Hint: glib2 [Processing]
        ... Hint: gtk2 [Processing]
        ... Hint: atk [Processing]
        ... Hint: pango [Processing]
        ... Hint: gdk2pixbuf [Processing]
        ... Hint: gdk2 [Processing]
        ... Hint: cairo [Processing]
        ... Hint: gtksourceview [Processing]
        ... Hint: dialogs [Processing]
        ... Hint: os [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: strformat [Processing]
        ... Hint: macros [Processing]
        ... Hint: posix [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: osproc [Processing]
        ... Hint: strtabs [Processing]
        ... Hint: hashes [Processing]
        ... Hint: streams [Processing]
        ... Hint: cpuinfo [Processing]
        ... Hint: linux [Processing]
        ... Hint: pegs [Processing]
        ... Hint: parseopt [Processing]
        ... Hint: asyncio [Processing]
        ... Hint: sockets [Processing]
        ... aporia.nim(14, 52) Warning: asyncio is deprecated [Deprecated]
        ... aporia.nim(14, 61) Warning: sockets is deprecated [Deprecated]
        ... Hint: encodings [Processing]
        ... Hint: tables [Processing]
        ... Hint: settings [Processing]
        ... Hint: utils [Processing]
        ... utils.nim(11, 60) Warning: asyncio is deprecated [Deprecated]
        ... Hint: CustomStatusBar [Processing]
        ... CustomStatusBar.nim(147, 17) Warning: < is deprecated [Deprecated]
        ... Hint: AboutDialog [Processing]
        ... utils.nim(289, 11) template/generic instantiation from here
        ... /home/floyd/.choosenim/toolchains/nim-0.19.4/lib/system.nim(471, 10) Error: 'nil' is now invalid for 'string'; compile with --nilseqs:on for a migration period; usage of '==' is a user-defined error
`

**Comment by Minimisthupper** [comment]
![image](https://user-images.githubusercontent.com/36794294/55683313-8a9e8600-593e-11e9-82df-3349d10d5876.png)
![image](https://user-images.githubusercontent.com/36794294/55683325-9ee28300-593e-11e9-8264-6823d36e5023.png)
![image](https://user-images.githubusercontent.com/36794294/55683331-a86beb00-593e-11e9-9656-b65827c82354.png)

**Comment by dom96** [comment]
Please use VS code, Aporia isn't supported very well anymore
