### ISSUE TITLE
Tabulation to spaces convertor

### ISSUE THREAD

**Issue by Trixarian** [nim-lang/Aporia#16]
Most code editors has this for convenience (and vice versa). Some uses the standard rule for tabulation to spaces conversion (4 spaces per tabulation), while others like geany pops up a dialog asking how many spaces should be used for each tabulation. This would be a nice feature to add to Aporia ;)

**Comment by ReneSac** [comment]
This is now already implemented as far as I can see.

**Comment by Trixarian** [comment]
It's now a feature, but wasn't 3 years ago. Why Dom left this open, I have no idea, but let's close it :frowning:
