### ISSUE TITLE
Doesn't build or run under Windows

### ISSUE THREAD

**Issue by mindplay-dk** [nim-lang/Aporia#51]
I attempted `nimrod c aporia` after fetching the current master/head, and it does not build - lots of warnings, then an error message.

``
C:\workspace\test\aporia>nimrod c aporia
c:\nimrod\config\nimrod.cfg(36, 11) Hint: added path: 'C:\Users\Rasmus Schultz\.babel\libs\' [Path]
Hint: used config file 'C:\nimrod\config\nimrod.cfg' [Conf]
Hint: used config file 'c:\workspace\test\aporia\aporia.nimrod.cfg' [Conf]
Hint: system [Processing]
Hint: aporia [Processing]
Hint: glib2 [Processing]
Hint: gtk2 [Processing]
Hint: atk [Processing]
Hint: pango [Processing]
Hint: gdk2pixbuf [Processing]
Hint: gdk2 [Processing]
Hint: gtksourceview [Processing]
Hint: dialogs [Processing]
Hint: windows [Processing]
Hint: shellapi [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: times [Processing]
Hint: winlean [Processing]
Hint: osproc [Processing]
Hint: strtabs [Processing]
Hint: hashes [Processing]
Hint: streams [Processing]
Hint: pegs [Processing]
Hint: unicode [Processing]
Hint: parseopt [Processing]
Hint: asyncio [Processing]
Hint: sockets [Processing]
Hint: encodings [Processing]
Hint: tables [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: settings [Processing]
Hint: utils [Processing]
Hint: aboutdialog [Processing]
Hint: customstatusbar [Processing]
customstatusbar.nim(92, 11) Hint: 'tid' is declared but not used [XDeclaredButNotUsed]
utils.nim(553, 11) Info: instantiation from here
c:\nimrod\lib\pure\pegs.nim(873, 14) Warning: injected 'matches' might be affected by new scoping rules in 0.9.4 [User]
Hint: cfg [Processing]
Hint: parsecfg [Processing]
Hint: lexbase [Processing]
Hint: search [Processing]
Hint: re [Processing]
Hint: pcre [Processing]
search.nim(60, 14) Hint: 'brackets' is declared but not used [XDeclaredButNotUsed]
search.nim(120, 13) Hint: 'matches' is declared but not used [XDeclaredButNotUsed]
Hint: suggest [Processing]
Hint: processes [Processing]
processes.nim(145, 14) Info: instantiation from here
c:\nimrod\lib\pure\pegs.nim(873, 14) Warning: injected 'matches' might be affected by new scoping rules in 0.9.4 [User]
processes.nim(162, 19) Info: instantiation from here
c:\nimrod\lib\pure\pegs.nim(873, 14) Warning: injected 'matches' might be affected by new scoping rules in 0.9.4 [User]
processes.nim(339, 12) Info: instantiation from here
c:\nimrod\lib\pure\streams.nim(42, 41) Warning: thread analysis incomplete due to unknown call 's.closeImpl(s)' [AnalysisLoophole]
processes.nim(343, 12) Warning: thread analysis incomplete due to unknown call 'close(p)' [AnalysisLoophole]
processes.nim(349, 17) Info: instantiation from here
c:\nimrod\lib\pure\streams.nim(51, 23) Warning: thread analysis incomplete due to unknown call 's.atEndImpl(s)' [AnalysisLoophole]
processes.nim(352, 21) Info: instantiation from here
c:\nimrod\lib\pure\streams.nim(185, 21) Info: instantiation from here
c:\nimrod\lib\pure\streams.nim(123, 14) Info: instantiation from here
c:\nimrod\lib\pure\streams.nim(76, 26) Warning: thread analysis incomplete due to unknown call 's.readDataImpl(s, buffer, bufLen)' [AnalysisLoophole]
Hint: rst [Processing]
Hint: rstast [Processing]
c:\nimrod\lib\packages\docutils\rst.nim(853, 20) Hint: 'dkAuthor' is declared but not used [XDeclaredButNotUsed]
c:\nimrod\lib\packages\docutils\rst.nim(1362, 6) Hint: 'rst.$(t: TToken): string' is declared but not used [XDeclaredButNotUsed]
c:\nimrod\lib\packages\docutils\rst.nim(853, 31) Hint: 'dkAuthors' is declared but not used [XDeclaredButNotUsed]
suggest.nim(66, 12) Warning: get_size is deprecated, get_width should be used [User]
suggest.nim(277, 13) Hint: 'f' is declared but not used [XDeclaredButNotUsed]
suggest.nim(412, 12) Hint: 'lang' is declared but not used [XDeclaredButNotUsed]
aporia.nim(699, 13) Error: undeclared field: 'set_upper'
``

I then fetched the last tagged release `0.1.1.0`, and while this did built, it does not run - when attempting to run from the shell, it silently exits without any message; when launched under a console, it outputs the following error message:

``
C:\workspace\test\aporia>aporia.exe
could not load: libgtksourceview-2.0-0.dll
``

As directed in the README, I did install the GTK runtimes, and made sure it's in my path.

I'm running Nimrod version 0.9.2 (2013-05-20).

Curious to see what the IDE looks like - since there are a lot of environmental dependencies, pre-built Windows binaries might be a good idea, as (sadly) you will seldomly find two Windows environments with the exact same configuration...

**Comment by jeremyflores** [comment]
I'm seeing this glib issue too on OSX. Is there a download available for that platform?

**Comment by dom96** [comment]
Unfortunately not, sorry.

**Comment by EnoughTea** [comment]
Clarification for those still struggling with this issue: only sane option is to build Aporia with x86 version of 'nim.exe'.

When built by x64 'nim.exe', Aporia requires x64 GTK runtime. GTK runtime versions for Windows, both "GtkSharp" and "GTK+ for Windows", are x86 only, at least for now. So even if you add their libraries to $PATH, they won't be linked.

Good news is, there is a x64 fork for GTK+ (https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer), albeit experimental, and pcre binaries are available for x64 architecture.

Bad news is, with gtksourceview your only option is to build it yourself against said experimental x64 GTK+ fork. Prebuilt x64 binary for Windows (which is linked in Aporia readme) is broken: there is no actual .dll file in any of the x64 gtksourceview packages.

So abandon all hope ye who enter 64-bit Aporia on Windows.

**Comment by skunkiferous** [comment]
As of now (29-09-2017), there is a x64 libgtksourceview-2.0-0.dll within [https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer]()  Unfortunately, a x64 built Aporia still says it cannot find it, at least in my system. Could this be reopened then?

**Comment by dom96** [comment]
Aporia isn't really maintained to be honest. You might be better off just using VS Code.
