### ISSUE TITLE
GC safety of handleRead in initSocket()

### ISSUE THREAD

**Issue by singularperturbation** [nim-lang/Aporia#56]
After [e6d17](https://github.com/Araq/Nimrod/commit/e6d17e62731a05110e464854eda79e891aaf2ff5) in asyncio.nim - made handleRead  and other procs GC-safe - there's a type mismatch with initSocket()'s handleRead (it needs to be declared with the gcsafe and closure pragmas).

I tried adding the {.gcsafe, closure.} pragmas to the anonymous proc's, but then got this:

    aporia.nim(2192, 8) Error: ':anonymous' is not GC-safe

I think it's because it's accessing the 'win' object?

It will still compile with

    nimrod --threadanalysis:off c aporia.nim

but I thought it would be worth an FYI.

Thanks!

**Comment by dom96** [comment]
This shouldn't be a problem once we rewrite to use async dispatcher instead of asyncio.
