### ISSUE TITLE
Installing Using nimble install Fails

### ISSUE THREAD

**Issue by belph** [nim-lang/Aporia#68]
I just attempted to install Aporia via nimble and received the following error:

    Hint: CustomStatusBar [Processing]
    CustomStatusBar.nim(41, 24) Error: undeclared identifier: 'False'
    FAILURE: Execution failed with exit code 1

This is all on a completely fresh nim/nimble install.

Also, the command shown on the readme no longer works. I needed to change `aporia#head` to `aporia` in order to get nimble to begin the installation (thus, the command which was run was `nimble install aporia`).

**Comment by dom96** [comment]
The command in the readme is incorrect. You're supposed to run ``nimble install aporia@#head``.
