### ISSUE TITLE
"SIGSEGV: Illegal storage access" running Aporia on OSX

### ISSUE THREAD

**Issue by keypusher** [nim-lang/Aporia#70]
Cloned latest Aporia from git, nim also running from latest Git.
Installed gtk+ via Homebrew (needed glib pango gtk+ gtksourceview)
On running Aporia, I get the following stacktrace.

Traceback (most recent call last)
aporia.nim(2454)         aporia
aporia.nim(2386)         initControls
aporia.nim(2125)         initTAndBP
aporia.nim(2110)         initBottomTabs
SIGSEGV: Illegal storage access.

**Comment by dom96** [comment]
Runs fine for me on OS X, closing.
