### ISSUE TITLE
Aporia stops working.

### ISSUE THREAD

**Issue by Tomatix** [nim-lang/Aporia#71]
So I dicsovered the Nim language yesterday and thought to give it a shot today.
Aporia worked fine to test some small stuff, but when I started it back up I got this message:
SIGSEGV: Illegal storage access. (Try to compile with -d:useSysAssert -d:useGcAssert for details.)

However, I figured pretty fast what caused it.
To reproduce the bug:
1. Start Aporia and type some simple code like echo("Hello")
2. Compile and run (F5)
3. Close Aporia without saving
4. Start Aporia

What causes this to crash is found in ~/.config/Aporia/config.auto.ini
[session]
tabs = r"/tmp/aporia/a0.nim|13;"
lastSelectedTab = r"/tmp/aporia/a0.nim"

That temporary file is, well, temporary, and may not exist when Aporia starts.
Resetting "tabs" and "lastSelectedTab" makes Aporia work again.

This issue can be somewhat discomforting in case someone deletes a source file that was on a previous session, causing Aporia not to start.

Summary: Aporia crashes when one of the files on previous session don't exist anymore.

**Comment by achesak** [comment]
This appears to have been fixed.

**Comment by dom96** [comment]
Please reopen/comment if it's not.
