### ISSUE TITLE
"could not load: libgdk-win32-2.0-0.dll"

### ISSUE THREAD

**Issue by ProtectedMode** [nim-lang/Aporia#75]
After building from source or installing via nimble, the following error appears when running:
```
could not load: libgdk-win32-2.0-0.dll
```
I've installed GTK and have the binary folder in my path, even when putting the dll in the Aporia directory, the error appears. 

Am I doing something wrong? Any help would be greatly appreciated.

**Comment by dom96** [comment]
Did you compile Aporia using a 64bit compiler?

**Comment by ProtectedMode** [comment]
@dom96, I probably did, but I can't tell for sure.

**Comment by ProtectedMode** [comment]
@dom96, yes, I used the 64 bit compiler. Is 64 bit not supported?

**Comment by dom96** [comment]
it should be as long as you get 64bit DLLs.
