### ISSUE TITLE
GTK Warning on windows

### ISSUE THREAD

**Issue by G4MR** [nim-lang/Aporia#77]
D:\Aporia>aporia.exe

    (aporia.exe:10344): Gtk-WARNING **: gtkliststore.c:253: Invalid type (null)

    Traceback (most recent call last)
    aporia.nim(2454)         aporia
    aporia.nim(2377)         initControls
    suggest.nim(540)         createSuggestDialog
    system.nim(3026)         failedAssertImpl
    system.nim(2239)         raiseAssert
    Error: unhandled exception: not (listStore == nil)  [AssertionError]

After properly getting the dependencies, adding all the gtk dll's to the aporia directory, that's th error I get.  On the latest nim build iirc.

**Comment by dom96** [comment]
Which compiler version are you using to compile aporia? Are you using the latest GTK2 wrappers?

**Comment by G4MR** [comment]
devel, issue was since I didn't install through nimble I didn't have the gtk2 nimble dependencies installed.  Since I just cloned the repo.  Readme's missing that little detail.

**Comment by dom96** [comment]
Assuming you got it working in the end. Closing.
