### ISSUE TITLE
Tools -> Compile * fails

### ISSUE THREAD

**Issue by Epidal** [nim-lang/Aporia#79]
Aporia expects gtksourceview to return "nimrod" as the ID for any *.nim files currently opened, but is receiving "nim" as that is the ID set in the gtksourceview language definition file.  Because of this, attempting to compile a Nim source file results in the error "Unable to determine what action to take for nim".

EDIT: I see this is fixed in the new-suggest branch, but hasn't been merged into the master branch yet.

**Comment by dom96** [comment]
This should be fixed now.
