### ISSUE TITLE
Can't compile on Linux: Error: undeclared identifier: '^'

### ISSUE THREAD

**Issue by thetyrelcorporation** [nim-lang/Aporia#81]
When trying to compile from source on Linux x86_64 I get the following output

    lots of gtk warnings
    ...
    home/tyger108/Apps/Aporia/utils.nim(454, 40) Error: undeclared identifier: '^'

**Comment by trustable-code** [comment]
I think you have to use Nim devel from git instead of Nim 0.10.2.

**Comment by dom96** [comment]
Yep. You need Nim devel.
