### ISSUE TITLE
Aporia crashes when it can't find Nim compiler executable

### ISSUE THREAD

**Issue by ReneSac** [nim-lang/Aporia#85]
Steps to reproduce:
 - Open aporia. It gives you an `a0.nim` file to work with.
 - Press F5

> Error: unhandled exception: No such file or directory [OSError]

~~I'm almost sure that doing this didn't crashed Aporia in the past.~~

**Comment by dom96** [comment]
I think this might be a config issue? Edit -> Preferences -> Tools, change ``findExe(nimrod...`` to ``findExe(nim...``

**Comment by ReneSac** [comment]
Indeed. Solved. Still, this shouldn't crash Aporia. It should display a window warning that the compiler was not found.

**Comment by dom96** [comment]
Indeed.
