### ISSUE TITLE
Error: cannot open 'glib2' on mac osx 10.10.3

### ISSUE THREAD

**Issue by Iancurtis** [nim-lang/Aporia#87]
config/nim.cfg(53, 3) Hint: added path: '/Users/jamie/.babel/pkgs/' [Path]
config/nim.cfg(54, 3) Hint: added path: '/Users/jamie/.nimble/pkgs/nimble-0.6.0' [Path]
config/nim.cfg(54, 3) Hint: added path: '/Users/jamie/.nimble/pkgs/' [Path]
Hint: used config file '/opt/Nim/config/nim.cfg' [Conf]
Warning: aporia.nimrod.cfg is deprecated [Deprecated]
Hint: used config file 'aporia.nimrod.cfg' [Conf]
Hint: system [Processing]
Hint: aporia [Processing]
opt/Aporia/aporia.nim(11, 8) Error: cannot open 'glib2'

I  did installed gtksourceview2 followed by the guide 
**port install gtksourceview2 libiconv
export LD_LIBRARY_PATH=/opt/local/lib/**

my system version:
`Darwin jamiedeMacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64`

**Comment by dom96** [comment]
Did you install gtk2 package from Nimble? ``nimble install gtk2@#head``

**Comment by Iancurtis** [comment]
I had opened an issue on Nimble about install error 
[https://github.com/nim-lang/nimble/issues/124](https://github.com/nim-lang/nimble/issues/124)

**Comment by Iancurtis** [comment]
`nimble install gtk2@#head `
passed the compilation.
