### ISSUE TITLE
aporia-0.3.0 can't focus on edit on win7 64

### ISSUE THREAD

**Issue by wwfifi** [nim-lang/Aporia#91]
When open 1+ files, switch between muti tabs, and  can't focus on edit, just show line number, codes is hide. Console and Errorlist alse has this problem.
![bug1](https://cloud.githubusercontent.com/assets/485018/7930361/3c23888e-093a-11e5-98f4-1940e8cc6ca1.png)

**Comment by dom96** [comment]
I need more information. Did you compile Aporia yourself? If not, where did you download it from. If yes, which version of Nim did you use?

**Comment by wwfifi** [comment]
Binarie 64 bit: nim-0.11.2_x64.exe from http://nim-lang.org/download.html

**Comment by dom96** [comment]
Can you try compiling a 32bit version?

**Comment by dom96** [comment]
Assuming this is a 32bit vs. 64bit problem. Reopen if you need more assistance.
