### ISSUE TITLE
autocompletion does not work on linux

### ISSUE THREAD

**Issue by tastyminerals** [nim-lang/Aporia#92]
On the example screenshot I noticed that Aporia provides autocompletion feature (correct me if I am wrong). However I don't have it working on my machine. I installed Aporia via nimble as was suggested here.

**Comment by tastyminerals** [comment]
Hm, for some reason didn't save the config. I checked the "enable suggest feature" and "ctrl+space" give me an error "could not find NimSuggest in PATH". 
Attemp to install "nimble install nimsuggest" failed with the following error:
```
~/.nimble/pkgs/compiler-0.10.3/compiler/nimfix/prettybase.nim(10, 8) Error: cannot open 'ast'
FAILURE: Execution failed with exit code 1
```

What is "ast"?

**Comment by krux02** [comment]
AST means *abstract syntax tree*, that is the parsed representation of the sourcecode used for a lot of ide features, and also macros.

**Comment by corytodd** [comment]
nimsuggest is installing fine and integrating with Aporia for me on Linux. I tried rolling back to Nim 10.2 but could not reproduce. Maybe something in Nimble has already been fixed?

**Comment by dom96** [comment]
Indeed. Even if this was still an issue it's not to do with Aporia.
