### ISSUE TITLE
problem with running: could not load: libgtksourceview-2.0.so(|.0)

### ISSUE THREAD

**Issue by Salafit** [nim-lang/Aporia#94]
I have installed aporia according instructions, but I have that problem. I have fedora 22  (64bit). 
I have installed also gtk2 (nimble install gtk2). My apologies for my English. Have you any idea?

**Comment by dom96** [comment]
Did you install the gtksourceview2 library using Fedora's package manager?

**Comment by Salafit** [comment]
Oh, noup)Even I didn't think that library exists in fedora's repos. Thank you! It's working now)
